sudo: false

dist: trusty

cache:
  apt: true
  directories:
    # Cache directory for older Composer versions.
    - $HOME/.composer/cache/files
    # Cache directory for more recent Composer versions.
    - $HOME/.cache/composer/files

language:
  - php

php:
  - 7.0
  - 7.1
  - 7.3
  - nightly

matrix:
  fast_finish: true
  include:
    # Seperate builds for PHP 7.2 with additional checks.
    - php: 7.2
      env: LINT=1 SNIFF=1
      addons:
        apt:
          packages:
            - libxml2-utils
    - php: 7.2

  allow_failures:
    # Allow failures for unstable builds.
    - php: nightly

before_install:
  # Speed up build time by disabling Xdebug.
  - phpenv config-rm xdebug.ini || echo 'No xdebug config.'
  - export XMLLINT_INDENT=" "
  - composer install --no-dev --no-suggest

script:
  # Lint the PHP files against parse errors.
  - if [[ "$LINT" == "1" ]]; then if find . -path ./vendor -prune -o -name "*.php" -exec php -l {} \; | grep "^[Parse error|Fatal error]"; then exit 1; fi; fi
  # Run the unit tests.
  - phpunit --filter Infinum $(pwd)/vendor/squizlabs/php_codesniffer/tests/AllTests.php
  # Check the codestyle of the Infinum codebase.
  - if [[ "$SNIFF" == "1" ]]; then composer check-cs .; fi
  # Validate the xml files.
  # @link http://xmlsoft.org/xmllint.html
  - if [[ "$SNIFF" == "1" ]]; then xmllint --noout ./*/ruleset.xml; fi
