sudo: false

dist: trusty

cache:
  apt: true
  directories:
    # Cache directory for older Composer versions.
    - $HOME/.composer/cache/files
    # Cache directory for more recent Composer versions.
    - $HOME/.cache/composer/files

language:
  - php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

matrix:
  fast_finish: true

  allow_failures:
    # Allow failures for unstable builds.
    - php: nightly

before_install:
  - sudo apt-get update
  - sudo apt-get -y install libxml2-utils

  # Speed up build time by disabling Xdebug.
  - phpenv config-rm xdebug.ini || echo 'No xdebug config.'
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:3} > "7.1" ]]; then composer require phpunit/phpunit:^7.0 --no-update --no-suggest --no-scripts;fi
  - composer install --dev --no-suggest

script:
  # Lint the PHP files against parse errors.
  - composer lint
  # Check the codestyle of the Infinum codebase.
  - composer check-cs
  # Validate the xml files.
  # @link http://xmlsoft.org/xmllint.html
  - xmllint --noout --schema ./vendor/squizlabs/php_codesniffer/phpcs.xsd ./*/ruleset.xml
  - xmllint --noout --schema ./vendor/squizlabs/php_codesniffer/phpcs.xsd ./phpcs.xml.dist.sample

  # Run the unit tests.
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:3} > "7.1" ]]; then
      vendor/bin/phpunit --filter WPThemeReview $(pwd)/vendor/squizlabs/php_codesniffer/tests/AllTests.php
    else
      phpunit --filter WPThemeReview $(pwd)/vendor/squizlabs/php_codesniffer/tests/AllTests.php
    fi
