name: "CI"

on:
  pull_request:
    branches: [ master, develop ]
  push:
    branches: [ master ]

jobs:
  php_lint:
    name: PHP lint on PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ 7.2, 7.3, 7.4 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: PHP setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Get composer cache directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install composer packages
        run: composer install --no-progress

      - name: Lint the project
        run: composer lint

  xml_lint:
    name: XML lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Download schema
        run: curl https://raw.githubusercontent.com/squizlabs/PHP_CodeSniffer/master/phpcs.xsd -o phpcs.xsd

      - name: Lint ruleset.xml
        uses: ChristophWurst/xmllint-action@v1
        with:
          xml-file: ./Infinum/ruleset.xml
          xml-schema-file: ./phpcs.xsd

  phpcs_check:
    name: PHPCS check on PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
            php: [ 7.2, 7.3, 7.4 ]

    steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: PHP setup
          uses: shivammathur/setup-php@v2
          with:
            php-version: ${{ matrix.php }}
            coverage: pcov

        - name: Get composer cache directory
          id: composer-cache
          run: |
            echo "::set-output name=dir::$(composer config cache-files-dir)"

        - name: Cache composer dependencies
          uses: actions/cache@v1
          with:
            path: ${{ steps.composer-cache.outputs.dir }}
            key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
            restore-keys: |
              ${{ runner.os }}-composer-

        - name: Install composer packages
          run: composer install --no-progress

        - name: Check coding standards using PHPCS
          run: composer standards:check -- --runtime-set testVersion ${{ matrix.php }}-

        - name: Check Infinum standards on example code
          run: composer tests:checkcs -- --runtime-set testVersion ${{ matrix.php }}-

  tests:
    name: Tests on PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
            php: [ 7.2, 7.3, 7.4 ]

    steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: PHP setup
          uses: shivammathur/setup-php@v2
          with:
            php-version: ${{ matrix.php }}
            coverage: pcov

        - name: Get composer cache directory
          id: composer-cache
          run: |
            echo "::set-output name=dir::$(composer config cache-files-dir)"

        - name: Cache composer dependencies
          uses: actions/cache@v1
          with:
            path: ${{ steps.composer-cache.outputs.dir }}
            key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
            restore-keys: |
              ${{ runner.os }}-composer-

        - name: Install composer packages
          run: composer install --no-progress

        - name: Run unit tests on the project
          run: composer tests:run
